/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef MINESWEEPER_PRIVATE_H
#define MINESWEEPER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.2.9"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	2
#define VER_BUILD	9
#define COMPANY_NAME	""
#define FILE_VERSION	"1.2.2.9"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"MineSweeper"
#define PRODUCT_VERSION	"1.2.2.9"

#endif /*MINESWEEPER_PRIVATE_H*/
